<h2><?php echo __('Recent Tweets:')?></h2>
<ul>
    <li>
        <a href="<?php echo $block->escapeHtml($block->getMagento2()) ?>">
            <span><?php echo __('Magento2')?></span>
        </a>
    </li>
    <li>
        <a href="<?php echo $block->escapeHtml($block->getMagentoDev()) ?>">
            <span><?php echo __('MagentoDev')?></span>
        </a>
    </li>
    <li>
        <a href="<?php echo $block->escapeHtml($block->getMagentoLive()) ?>">
            <span><?php echo __('MagentoLive')?></span>
        </a>
    </li>
</ul>